sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123123

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tFcQ5Nknhqus1fCnR4u
    access-key-secret: LxOsuWe3Lrj0gUR9Q6dnCHnSElYLB1
    bucket-name: skyhhhh123

  wechat:
    appid: wx13c5ba639bc0f1ed
    secret: 9f7d0d325023db7f82b1775422fa3fee